# Generated by Django 4.2.1 on 2023-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatordata',
            name='deliveryPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calculatordata',
            name='deliveryTime',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='deliveryMethod',
            field=models.CharField(blank=True, default='Авто', max_length=50, null=True),
        ),
    ]
