# Generated by Django 4.2.1 on 2023-07-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_feedback_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='hello1', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='MoscowPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='hello1', upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
